import { t } from "elysia";

export const paymentMethodSchema = t.Enum({
  CASH: "CASH",
  KBZ_PAY: "KBZ_PAY",
  CB_PAY: "CB_PAY",
  WAVE_PAY: "WAVE_PAY",
  CARD: "CARD",
  BANK_TRANSFER: "BANK_TRANSFER",
  MIXED_PAYMENT: "MIXED_PAYMENT",
  GIFT_CARD: "GIFT_CARD",
  WALLET: "WALLET",
});

export const roleSchema = t.Enum({
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  CASHIER: "CASHIER",
  ACCOUNTANT: "ACCOUNTANT",
});

export const permissionSchema = t.Enum({
  VIEW_REPORTS: "VIEW_REPORTS",
  EDIT_PRICES: "EDIT_PRICES",
  VOID_ORDERS: "VOID_ORDERS",
  MANAGE_STAFF: "MANAGE_STAFF",
  MANAGE_INVENTORY: "MANAGE_INVENTORY",
  REFUND_ORDERS: "REFUND_ORDERS",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
  MANAGE_PROMOTIONS: "MANAGE_PROMOTIONS",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  MANAGE_API_KEYS: "MANAGE_API_KEYS",
  MANAGE_WEBHOOKS: "MANAGE_WEBHOOKS",
});

export const movementTypeSchema = t.Enum({
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  RETURN_IN: "RETURN_IN",
  RETURN_OUT: "RETURN_OUT",
  ADJUSTMENT: "ADJUSTMENT",
  DAMAGE: "DAMAGE",
  EXPIRED: "EXPIRED",
  TRANSFER_IN: "TRANSFER_IN",
  TRANSFER_OUT: "TRANSFER_OUT",
  OPENING_STOCK: "OPENING_STOCK",
  COUNTING: "COUNTING",
});

export const orderStatusSchema = t.Enum({
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  VOIDED: "VOIDED",
  REFUNDED: "REFUNDED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED",
  HOLD: "HOLD",
});

export const auditActionSchema = t.Enum({
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  RESTORE: "RESTORE",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  EXPORT: "EXPORT",
  PRINT: "PRINT",
  VOID: "VOID",
  REFUND: "REFUND",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
});

export const notificationTypeSchema = t.Enum({
  LOW_STOCK: "LOW_STOCK",
  EXPIRING_PRODUCT: "EXPIRING_PRODUCT",
  ORDER_STATUS: "ORDER_STATUS",
  PROMOTION: "PROMOTION",
  SYSTEM: "SYSTEM",
  INVENTORY_COUNT: "INVENTORY_COUNT",
});

export const discountTypeSchema = t.Enum({
  PERCENTAGE: "PERCENTAGE",
  FIXED_AMOUNT: "FIXED_AMOUNT",
  BUY_X_GET_Y: "BUY_X_GET_Y",
  FREE_SHIPPING: "FREE_SHIPPING",
});

export const customerTierSchema = t.Enum({
  BRONZE: "BRONZE",
  SILVER: "SILVER",
  GOLD: "GOLD",
  PLATINUM: "PLATINUM",
  DIAMOND: "DIAMOND",
});

export const giftCardStatusSchema = t.Enum({
  ACTIVE: "ACTIVE",
  USED: "USED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
});

export const walletTransactionTypeSchema = t.Enum({
  DEPOSIT: "DEPOSIT",
  WITHDRAWAL: "WITHDRAWAL",
  PAYMENT: "PAYMENT",
  REFUND: "REFUND",
  ADJUSTMENT: "ADJUSTMENT",
});
