services:
  db:
    image: postgres:16-alpine
    container_name: pos_database
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - pgdata:/var/lib/postgresql/data

    expose:
      - "5432"

    networks:
      - mynetwork

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pos_server
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV:-development}

    ports:
      - "6060:6060"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - mynetwork

    # healthcheck:
    #   test: ["CMD-SHELL", "wget --spider -q http://localhost:6060 || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 20s

    # Development only
    volumes:
      - .:/app:Z
      - /app/node_modules

  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: pos_prisma_studio

    command: >
      sh -c "npx prisma studio
      --hostname 0.0.0.0
      --port 5555"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

    ports:
      - "5555:5555"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - mynetwork

    profiles:
      - dev
      - studio

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: pos_tunnel

    command: tunnel --no-autoupdate run

    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}

    restart: unless-stopped

    # depends_on:
    #   - app
    # app:
    # condition: service_healthy

    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
