services:
  db:
    image: postgres:16-alpine
    container_name: pos_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: posdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d posdb"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: .
    container_name: pos_server
    env_file:
      - .env
    ports:
      - "6060:6060"
    volumes: #may be cna delete this
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/posdb"
      JWT_SECRET: "supersecret"
    command: >
      sh -c "bun x prisma generate && bun run src/index.ts"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - mynetwork

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: pos_tunnel
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    #  tunnel --no-autoupdate run --token
    networks:
      - mynetwork
    depends_on:
      - app
    restart: always

volumes:
  pgdata:

networks:
  mynetwork:
